# Generated by Django 4.0.6 on 2023-07-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

operations = [
    migrations.RunSQL(
        'ALTER SEQUENCE MAIN_STUDENT_id_seq RESTART WITH 10000;'
    )
]
