# Generated by Django 4.0.6 on 2023-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_student_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
