# Generated by Django 4.0.6 on 2023-07-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=None, max_length=60)),
                ('Date', models.DateField()),
                ('Function', models.CharField(help_text='Function name like Open House, Certfication Day and Picnic etc', max_length=40)),
            ],
        ),
    ]
