# Generated by Django 4.0.6 on 2023-07-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
