# Generated by Django 4.0.6 on 2023-07-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
